---
title: "Simple document"
author: "Jeff Goldsmith"
date: 2024-09-10
output:
  html_document :
  toc: true
  toc_float: true
---

I'm an R Markdown document! 

# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r}  
samp = rnorm(100)
length(samp)
```

```{r eval = FALSE}  
samp = rnorm(50)
length(samp)
```
```{r echo = FALSE}  
samp = rnorm(10)
length(samp)
```

# Section 2

I can take the mean of the sample, too!
The mean is `r mean(samp)`.

# Learning assessment 1
```{r Learning_Assessment_1}
library(tidyverse)
la_df = tibble(
  norm_samp = rnorm(500, mean = 1),
  norm_samp_flag = norm_samp > 0,
  abs_norm_samp = abs(norm_samp)
)
ggplot(la_df, aes(x = abs_norm_samp)) + geom_histogram()

median_samp = median(pull(la_df, norm_samp))
```

# Format

Text formatting 
------------------------------------------------------------

*italic*  or  _italic_

**bold**  or  __bold__

`code`

superscript^2^ and subscript~2~


Headings
------------------------------------------------------------

# 1st Level Header

## 2nd Level Header

### 3rd Level Header


Lists
------------------------------------------------------------

*   Bulleted list item 1

*   Item 2

    * Item 2a

    * Item 2b

1.  Numbered list item 1

1.  Item 2. The numbers are incremented automatically in the output.


Tables 
------------------------------------------------------------

First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell